# Generated by Django 3.2 on 2021-04-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210421_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchar',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameuser', to='app.game'),
        ),
        migrations.AlterField(
            model_name='gamerules',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamerule', to='app.game'),
        ),
    ]
